/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as NewCampaignRouteImport } from './routes/new-campaign'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CampaignsNameRouteImport } from './routes/campaigns.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const NewCampaignRoute = NewCampaignRouteImport.update({
  id: '/new-campaign',
  path: '/new-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNameRoute = CampaignsNameRouteImport.update({
  id: '/campaigns/$name',
  path: '/campaigns/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/inbox': typeof InboxRoute
  '/invites': typeof InvitesRoute
  '/new-campaign': typeof NewCampaignRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$name': typeof CampaignsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/inbox': typeof InboxRoute
  '/invites': typeof InvitesRoute
  '/new-campaign': typeof NewCampaignRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$name': typeof CampaignsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/inbox': typeof InboxRoute
  '/invites': typeof InvitesRoute
  '/new-campaign': typeof NewCampaignRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$name': typeof CampaignsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/inbox'
    | '/invites'
    | '/new-campaign'
    | '/settings'
    | '/campaigns/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/inbox'
    | '/invites'
    | '/new-campaign'
    | '/settings'
    | '/campaigns/$name'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/inbox'
    | '/invites'
    | '/new-campaign'
    | '/settings'
    | '/campaigns/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  InboxRoute: typeof InboxRoute
  InvitesRoute: typeof InvitesRoute
  NewCampaignRoute: typeof NewCampaignRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsNameRoute: typeof CampaignsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-campaign': {
      id: '/new-campaign'
      path: '/new-campaign'
      fullPath: '/new-campaign'
      preLoaderRoute: typeof NewCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$name': {
      id: '/campaigns/$name'
      path: '/campaigns/$name'
      fullPath: '/campaigns/$name'
      preLoaderRoute: typeof CampaignsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  InboxRoute: InboxRoute,
  InvitesRoute: InvitesRoute,
  NewCampaignRoute: NewCampaignRoute,
  SettingsRoute: SettingsRoute,
  CampaignsNameRoute: CampaignsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
